[project]
name = "pem-birefringence"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.5",
    "pyvisa>=1.15.0",
    "scipy>=1.15.2",
]
